name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      id-token: write
      contents: write

    uses: NathanVaughn/reusable-actions/.github/workflows/pypi-publish.yml@main